"""
CSV/JSON export with methodology documentation for backtesting results.

Export functions produce investor-grade output with a self-documenting
methodology section that describes evaluation parameters, bias prevention
measures, and metric definitions. Every exported file is auditable
without requiring a separate explanation document.
"""

from __future__ import annotations

import csv
import io
import logging
from datetime import datetime
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.db.models import BacktestResult, BacktestRun

logger = logging.getLogger(__name__)


METHODOLOGY_TEMPLATE: str = """\
# Backtesting Methodology

## Walk-Forward Evaluation

This evaluation uses a walk-forward (expanding/sliding window) approach
to assess historical prediction accuracy without look-ahead bias.

- **Window size:** {window_size_days} days
- **Slide step:** {slide_step_days} days (windows overlap by \
{overlap_pct:.0f}%)
- **Minimum predictions per window:** {min_predictions_per_window}
- **Evaluation scope:** All resolved predictions (organic + \
Polymarket-driven)

For each window [t0, t0+W]:
  1. A "context window" defines the training boundary.
  2. Predictions created in the next [t0+W, t0+2W] interval are \
re-evaluated.
  3. Metrics are computed against ground-truth outcomes.

## Bias Prevention Measures

### 1. Calibration Weight Snapshots
Per-CAMEO calibration weights are reconstructed from \
calibration_weight_history as they existed at each window boundary. \
Current weights (which have seen future outcomes) are never used. \
Codes with no calibration history at the window date fall back to \
literature-derived cold-start priors.

### 2. Ephemeral ChromaDB Temporal Indexes
The RAG pipeline retrieves articles from a ChromaDB vector store. For \
each evaluation window, an ephemeral in-memory index is built containing \
only articles published on or before the window's end date. This makes \
look-ahead bias through article retrieval physically impossible. Date \
filtering is done in Python (not relying on ChromaDB string comparison) \
to handle inconsistent date formats across RSS feeds. Indexes are not \
cached on disk -- each run rebuilds from source.

### 3. Fresh EnsemblePredictor Per Prediction
Each re-prediction uses a newly constructed EnsemblePredictor instance \
to prevent mutable internal state from leaking between predictions.

## Metric Definitions

### Brier Score
BS = (1/N) * sum((predicted_i - outcome_i)^2)
Range: [0, 1]. Lower is better. Random baseline = 0.25.

### Calibration Bins (Reliability Diagram)
Predictions are bucketed into 10 equal-width bins [0.0, 0.1), [0.1, \
0.2), ..., [0.9, 1.0]. For each bin: mean predicted probability and \
observed outcome frequency. Perfect calibration: predicted_avg == \
observed_freq for all bins.

### Hit Rate
Binary classification accuracy at threshold 0.5. A prediction is \
correct if (predicted >= 0.5 AND outcome == 1) OR (predicted < 0.5 \
AND outcome == 0).

### MRR (Mean Reciprocal Rank)
TKG model ranking quality: MRR = (1/N) * sum(1/rank_i). Only computed \
when TKG ranking data is available.

### Geopol vs Polymarket
Head-to-head Brier score comparison on co-evaluated questions. \
Winner = lower Brier score per prediction. Only includes predictions \
with resolved Polymarket comparison data.

## Data Sources
All predictions in the database are eligible regardless of provenance. \
This includes organic forecasts (pipeline-generated), Polymarket-driven \
forecasts, and Polymarket-tracked forecasts. Inclusion criteria: the \
prediction must have a resolved outcome_record within the evaluation \
window.

## Model Checkpoints
{checkpoints_desc}

---
Generated by Geopol Backtesting Engine v1.0
"""


def _format_methodology(run: BacktestRun) -> str:
    """Fill the methodology template with run-specific parameters."""
    overlap_pct = (
        (1.0 - run.slide_step_days / run.window_size_days) * 100
        if run.window_size_days > 0
        else 0.0
    )

    checkpoints = run.checkpoints_json or {}
    if checkpoints:
        lines = [f"- **{name}:** {path}" for name, path in checkpoints.items()]
        checkpoints_desc = "\n".join(lines)
    else:
        checkpoints_desc = "Default model checkpoint (no explicit selection)."

    return METHODOLOGY_TEMPLATE.format(
        window_size_days=run.window_size_days,
        slide_step_days=run.slide_step_days,
        overlap_pct=overlap_pct,
        min_predictions_per_window=run.min_predictions_per_window,
        checkpoints_desc=checkpoints_desc,
    )


def _run_to_dict(run: BacktestRun) -> dict[str, Any]:
    """Serialize a BacktestRun ORM object to a plain dict."""
    return {
        "id": run.id,
        "label": run.label,
        "description": run.description,
        "window_size_days": run.window_size_days,
        "slide_step_days": run.slide_step_days,
        "min_predictions_per_window": run.min_predictions_per_window,
        "checkpoints": run.checkpoints_json,
        "status": run.status,
        "started_at": run.started_at.isoformat() if run.started_at else None,
        "completed_at": run.completed_at.isoformat() if run.completed_at else None,
        "total_windows": run.total_windows,
        "completed_windows": run.completed_windows,
        "total_predictions": run.total_predictions,
        "aggregate_brier": run.aggregate_brier,
        "aggregate_mrr": run.aggregate_mrr,
        "vs_polymarket_record": run.vs_polymarket_record_json,
        "created_at": run.created_at.isoformat() if run.created_at else None,
    }


def _result_to_dict(r: BacktestResult) -> dict[str, Any]:
    """Serialize a BacktestResult ORM object to a plain dict."""
    return {
        "id": r.id,
        "run_id": r.run_id,
        "window_start": r.window_start.isoformat() if r.window_start else None,
        "window_end": r.window_end.isoformat() if r.window_end else None,
        "prediction_start": r.prediction_start.isoformat() if r.prediction_start else None,
        "prediction_end": r.prediction_end.isoformat() if r.prediction_end else None,
        "checkpoint_name": r.checkpoint_name,
        "num_predictions": r.num_predictions,
        "brier_score": r.brier_score,
        "mrr": r.mrr,
        "hits_at_1": r.hits_at_1,
        "hits_at_10": r.hits_at_10,
        "calibration_bins": r.calibration_bins_json,
        "prediction_details": r.prediction_details_json,
        "polymarket_brier": r.polymarket_brier,
        "geopol_vs_pm_wins": r.geopol_vs_pm_wins,
        "pm_vs_geopol_wins": r.pm_vs_geopol_wins,
        "weight_snapshot": r.weight_snapshot_json,
        "created_at": r.created_at.isoformat() if r.created_at else None,
    }


async def export_run_json(
    session: AsyncSession,
    run_id: str,
) -> dict[str, Any]:
    """Export a single backtest run as a JSON-serializable dict.

    Includes run metadata, all window results, aggregate metrics,
    and a methodology section documenting evaluation parameters and
    bias prevention measures.

    Args:
        session: Async SQLAlchemy session.
        run_id: UUID of the backtest run.

    Returns:
        Dict suitable for json.dumps().

    Raises:
        ValueError: If run_id not found.
    """
    run = await session.get(BacktestRun, run_id)
    if run is None:
        raise ValueError(f"BacktestRun {run_id} not found")

    results_stmt = (
        select(BacktestResult)
        .where(BacktestResult.run_id == run_id)
        .order_by(BacktestResult.window_start.asc())
    )
    results_result = await session.execute(results_stmt)
    results = results_result.scalars().all()

    return {
        "run": _run_to_dict(run),
        "windows": [_result_to_dict(r) for r in results],
        "methodology": _format_methodology(run),
    }


async def export_run_csv(
    session: AsyncSession,
    run_id: str,
) -> str:
    """Export a single backtest run as a CSV string.

    Includes a methodology comment block at the top, followed by
    per-window metric rows.

    Args:
        session: Async SQLAlchemy session.
        run_id: UUID of the backtest run.

    Returns:
        CSV string with headers and data rows.

    Raises:
        ValueError: If run_id not found.
    """
    run = await session.get(BacktestRun, run_id)
    if run is None:
        raise ValueError(f"BacktestRun {run_id} not found")

    results_stmt = (
        select(BacktestResult)
        .where(BacktestResult.run_id == run_id)
        .order_by(BacktestResult.window_start.asc())
    )
    results_result = await session.execute(results_stmt)
    results = results_result.scalars().all()

    output = io.StringIO()

    # Methodology as comment block.
    methodology = _format_methodology(run)
    for line in methodology.splitlines():
        output.write(f"# {line}\n")
    output.write("#\n")

    # Run summary.
    output.write(f"# Run: {run.label}\n")
    output.write(f"# Status: {run.status}\n")
    output.write(f"# Aggregate Brier: {run.aggregate_brier}\n")
    output.write(f"# Aggregate MRR: {run.aggregate_mrr}\n")
    output.write(f"# Total Predictions: {run.total_predictions}\n")
    output.write("#\n")

    # CSV data.
    writer = csv.writer(output)
    writer.writerow([
        "window_start",
        "window_end",
        "checkpoint",
        "num_predictions",
        "brier_score",
        "mrr",
        "hits_at_1",
        "hits_at_10",
        "polymarket_brier",
        "geopol_wins",
        "pm_wins",
    ])

    for r in results:
        writer.writerow([
            r.window_start.isoformat() if r.window_start else "",
            r.window_end.isoformat() if r.window_end else "",
            r.checkpoint_name,
            r.num_predictions,
            r.brier_score,
            r.mrr,
            r.hits_at_1,
            r.hits_at_10,
            r.polymarket_brier,
            r.geopol_vs_pm_wins,
            r.pm_vs_geopol_wins,
        ])

    return output.getvalue()


async def export_multi_run_json(
    session: AsyncSession,
    run_ids: list[str],
) -> dict[str, Any]:
    """Merge multiple backtest runs into a single export.

    Groups window results by run label, enabling cross-run comparison
    in external tools (Python, R, Excel).

    Args:
        session: Async SQLAlchemy session.
        run_ids: List of backtest run UUIDs to include.

    Returns:
        Dict with run labels as group identifiers and merged results.
    """
    runs_data: list[dict[str, Any]] = []

    for run_id in run_ids:
        run_export = await export_run_json(session, run_id)
        runs_data.append(run_export)

    return {
        "runs": runs_data,
        "comparison_note": (
            "Each run contains its own methodology section. Window results "
            "are grouped by run label for cross-run comparison."
        ),
    }
